### ISSUE TITLE
💡 [REQUEST] - Extension for VS Codium

### ISSUE THREAD

**Issue by porwalshreyaa** [devarshishimpi/lunar-vscode-theme#1]
### Start Date

06/25/2024

### Summary

I use VS Codium as my go to code editor and not Code. It's completely like VS code, just the vs codium marketplace is different. Please add it to VS Codium Market place.

### Drawbacks

I use VS Codium as my go to code editor and not Code.

**Comment by devarshishimpi** [comment]
Thanks for raising the issue! Will definitely work on this.

**Comment by devarshishimpi** [comment]
Once I have the namespace access, it should resolve this issue.

https://github.com/EclipseFdn/open-vsx.org/issues/2773

**Comment by devarshishimpi** [comment]
Published, fixed from https://github.com/prismlinkapp/lunar-vscode-theme/commit/b23cb17d3fec26310b221dd6e641c3971a7e05e6
